### ISSUE TITLE
next edits

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/thesis-guide-deprec#3]
- [x] resize pictures, to text width, see example in index.md for content + process
- [x] move images to a separate directory (root/docs/assets). Right now, they start to clutter the docs directory.
- [x] replace "slide" working, rather link to pages (e.g., see next slides 2 is irrelevant as this is a website now; rather link to introduction and literature review)
- [x] sometimes you are missing text from the original slide: e.g., in the content/introduction: How to write it up… (e.g., in your introduction or XXXXXX
- [x] try to be precise; here, you're missing the ITALICS (*text*)
![afbeelding](https://user-images.githubusercontent.com/16557730/70181271-e42f9e00-16e1-11ea-99f7-71c1e6f40115.png)
- [x] type in jornals (should be "Journals")

**Comment by hannesdatta** [comment]
- [x] you can make these changes; THEN, go ahead with the rest of the thesis guide, please.

**Comment by msali123** [comment]
Committing with the changes and pushing to update branch

**Comment by msali123** [comment]
Done with all the fixes and committed
